### ISSUE TITLE
Crash when run on a large project

### ISSUE THREAD

**Issue by MRajcic** [dlidstrom/Duplo#47]
Trying to run duplo on large project (MySQL sources), it crashes with std::bad_alloc exception:
```
Run duplo on sources...
Loading and hashing files ... 11100 done.

std::bad_alloc
```

I've run the tool, built from sources (just "cmake"), on Ubuntu 24.04 Linux running under WSL (Windows subsystem for Linux) v1, on laptop having 32GB RAM.
The script running it is similar to the one described here on GitHub:
```
find ../git/mysql -type f \( -iname "*.cpp" -o -iname "*.cc" -o -iname "*.h" -o -iname "*.hh" -o -iname "*.hpp" -o -iname "*.ic" -o -iname "*.i"  \)> files.lst
duplo files.lst log_duplo.txt
```

If I edit file list manually, and leave 10 file paths in it, duplo works OK.

Are there any practical limits on project size that the duplo can handle?
Any plans to make it less RAM hungry (store some intermediate results to disk, for example)?

**Comment by dlidstrom** [comment]
Hi @MRajcic ! Thanks for your report. Are you actively developing MySQL and looking for duplicated code? If so, then I think you should limit searches to specific feature areas as you're not very likely to find duplicates across the entire code base. If you're not actively developing MySQL, then yes you have found a limitation in Duplo. It needs to keep a bit of information in memory. No there are no fancy plans like you suggest. Good to hear it works OK otherwise and Good luck on your refactoring!

**Comment by MRajcic** [comment]
Thank you for the feedback.
Yes, I am a MySQL developer and tried to see what interesting info I could get by checking the code duplication on entire repository. 
I got the duplo working OK by restricting the run to ~ 2500 files, so closing the issue.
